name: kiwi

on:
  push:
    branches: [ "unstable" ]
  pull_request:
    branches: [ "unstable" ]

env:
  BUILD_DIR: cmake-build-release

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: bash ./etc/script/ci/build.sh

      - name: Check Format
        working-directory: ${{ github.workspace }}/build
        run: make check-format

  build_on_macos:
    runs-on: macos-12
    needs: check_format

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          brew install autoconf
          brew install go
          bash ./etc/script/build.sh --verbose

      - name: GTest
        working-directory: ${{ github.workspace }}/${{ env.BUILD_DIR }}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest

      - name: Run TCL E2e Tests
        working-directory: ${{ github.workspace }}
        run:
          ./etc/script/kiwitests.sh all

      - name: Run Go E2E Tests
        working-directory: ${{ github.workspace }}/${{ env.BUILD_DIR }}
        run: |
          set +e
          cd ../tests
          go mod tidy
          go test -timeout 15m --ginkgo.v
          sh print_log.sh

  build_on_ubuntu:
    runs-on: ubuntu-latest
    needs: check_format

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          bash ./etc/script/build.sh --verbose

      - name: GTest
        working-directory: ${{ github.workspace }}/${{ env.BUILD_DIR }}
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest

      - name: Run TCL E2e Tests
        working-directory: ${{ github.workspace }}
        run:
          ./etc/script/kiwitests.sh all

      - name: Run Go E2E Tests
        working-directory: ${{ github.workspace }}/${{ env.BUILD_DIR }}
        run: |
          set +e
          cd ../tests
          go mod tidy
          go test -timeout 15m --ginkgo.v
          sh print_log.sh
